### PR TITLE
fix program panic when deleted a legacy mo cluster

### LINKED ISSUE #328: [Bug]: mo-operator panic on deletion
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id (e.g. v0.1.0 or 8b23a93): https://github.com/matrixorigin/matrixone-operator/commit/e601fa3a8e37237c5b45c2e6d34e0cafa0ea5d17
- Hardware parameters:
- OS type:
- Others:

### Actual Behavior

```
2023-04-17T09:52:43Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "logset", "controllerGroup": "core.matrixorigin.io", "controllerKind": "LogSet", "LogSet": {"name":"daily-mo-dis","namespace":"mo-dailybuild"}, "namespace": "mo-dailybuild", "name": "daily-mo-dis", "reconcileID": "42cd4be3-f2ec-4d80-85cd-26fedc3b4471"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14881a0]

goroutine 527 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x1626040, 0x25d39a0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/matrixorigin/matrixone-operator/pkg/controllers/logset.(*Actor).finalizeBucket(0xc00012ea60?, 0xc00113ef60)
	/workspace/pkg/controllers/logset/bucketclaim.go:92 +0x320
github.com/matrixorigin/matrixone-operator/pkg/controllers/logset.(*Actor).Finalize(0x1a625e0?, 0xc00113ef60)
	/workspace/pkg/controllers/logset/controller.go:302 +0x585
github.com/matrixorigin/controller-runtime/pkg/reconciler.(*Reconciler[...]).finalize(0xc0002bc1c0, 0xc00113ef60)
	/go/pkg/mod/github.com/matrixorigin/controller-runtime@v0.0.0-20230329033025-17c57685ca8e/pkg/reconciler/reconciler.go:324 +0x63
github.com/matrixorigin/controller-runtime/pkg/reconciler.(*Reconciler[...]).Reconcile(0xc0002bc1c0, {0x1a75c38, 0xc0008891a0?}, {{{0xc00012ea60, 0x0?}, {0xc00012ea50?, 0x7f144ff27eb0?}}})
	/go/pkg/mod/github.com/matrixorigin/controller-runtime@v0.0.0-20230329033025-17c57685ca8e/pkg/reconciler/reconciler.go:192 +0xea8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1a75c38?, {0x1a75c38?, 0xc0008891a0?}, {{{0xc00012ea60?, 0x15acba0?}, {0xc00012ea50?, 0x413fb4?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000b5720, {0x1a75b90, 0xc000723480}, {0x167ca60?, 0xc0004af700?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323 +0x386
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000b5720, {0x1a75b90, 0xc000723480})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:231 +0x325
```

### Expected Behavior

mo should not panic on deletion

### Steps to Reproduce

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by loveRhythm1990**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #328

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

File: api/core/v1alpha1/logset_types.go [hunk 1]
```diff
@@ -87,11 +87,21 @@ func (l *LogSetBasic) GetStoreFailureTimeout() metav1.Duration {
 
 func (l *LogSetBasic) GetPVCRetentionPolicy() PVCRetentionPolicy {
 	if l.PVCRetentionPolicy == nil {
-		return PVCRetentionPolicyDelete
+		l.setDefaultRetentionPolicy()
 	}
 	return *l.PVCRetentionPolicy
 }
 
+func (l *LogSetBasic) GetS3RetentionPolicy() *PVCRetentionPolicy {
```
Comment (aylei) [inline api/core/v1alpha1/logset_types.go:95]: How about add this method to the "S3" struct? So that we simply call `l.SharedStorage.S3.GetRetentionPolicy()`, which is automatically namespaced

File: api/core/v1alpha1/bucketclaim_helpers.go [hunk 2]
```diff
@@ -71,6 +71,9 @@ func BucketBindToMark(logsetMeta metav1.ObjectMeta) string {
 }
 
 func AddBucketFinalizer(ctx context.Context, c client.Client, lsMeta metav1.ObjectMeta, finalizer string) error {
+	if lsMeta.Namespace == "" || lsMeta.Name == "" {
+		return nil
+	}
```
Comment (aylei) [inline api/core/v1alpha1/bucketclaim_helpers.go:76]: Is this possible?

Comment (loveRhythm1990) [reply api/core/v1alpha1/bucketclaim_helpers.go:76]: probably impossible, may be I am too sensitive

File: api/core/v1alpha1/logset_types.go (hunk 1 above)
Comment (loveRhythm1990) [reply api/core/v1alpha1/logset_types.go:95]: S3 retention policy is related to pvc retention policy, I think it is batter set in logsetbasic scope

Comment (aylei) [reply api/core/v1alpha1/logset_types.go:95]: got it

**Review by aylei — APPROVED** [review]
lgtm
